name: alkambio_flutter
description: An open-source currency exchange rate app for Venezuela.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^9.1.1
  
  # API & Network
  http: ^1.2.1
  
  # Dependency Injection
  get_it: ^8.2.0
  injectable: ^2.3.2
  
  # Models & Equality
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  
  # Utils
  intl: ^0.20.2
  dartz: ^0.10.1
  package_info_plus: ^9.0.0

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.8.1
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
